jobs:
  include:
    - language: java
      jdk: oraclejdk17
      before_install:
        - sudo apt-get update
        - cd backend/
        - mvn clean package -Dmaven.test.skip
      script: docker-compose build
      before_deploy:
        - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      deploy:
        - provider: script
          script:
            docker tag dsmovie-backend:latest $DOCKER_USERNAME/dsmovie-backend:$TRAVIS_JOB_ID;
            docker tag dsmovie-frontend:latest $DOCKER_USERNAME/dsmovie-frontend:$TRAVIS_JOB_ID;
            docker push $DOCKER_USERNAME/dsmovie-backend:$TRAVIS_JOB_ID;
            docker push $DOCKER_USERNAME/dsmovie-frontend:$TRAVIS_JOB_ID;
          on:
            branch: main
          skip_cleanup: true
        - provider: heroku
          api_key:
            secure: $HEROKU_API_KEY
          on:
            branch: main
          skip_cleanup: true

    - language: node_js
      node_js: 16
      before_script:
        - cd frontend/
      script:
        - yarn install

notifications:
  email: false
