jobs:
  include:
    - language: java
      jdk: oraclejdk17
      before_install:
        - sudo apt-get update
        - cd backend/
        - mvn clean package -Dmaven.test.skip
        - cd ../frontend/
        - yarn install
      script: docker-compose build
      before_deploy:
        - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      deploy:
        skip_cleanup: true
        provider: script
        script:
          docker tag dsmovie-backend:latest $DOCKER_USERNAME/dsmovie-backend:$TRAVIS_JOB_ID;
          docker tag dsmovie-frontend:latest $DOCKER_USERNAME/dsmovie-frontend:$TRAVIS_JOB_ID;
          docker push $DOCKER_USERNAME/dsmovie-backend:$TRAVIS_JOB_ID;
          docker push $DOCKER_USERNAME/dsmovie-frontend:$TRAVIS_JOB_ID;
        on:
          branch: main

notifications:
  email: false
