jobs:
  include:
    - language: java
      jdk: oraclejdk17
      before_script:
        - cd backend/
      script:
        - mvn clean package -Dmaven.test.skip
      on:
        branch: main

    - language: node_js
      node_js: 16
      before_script:
        - cd frontend/
      script:
        - yarn install
notifications:
  email: false
