jobs:
  include:
    - language: java
      jdk: oraclejdk17
      before_script:
        - cd backend/
      script:
        - mvn clean package -Dmaven.test.skip
      before_deploy:
        - docker-compose build
        - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        deploy:
          skip_cleanup: true
          provider: script
          script:
            docker tag dsmovie-backend:latest $DOCKER_USERNAME/dsmovie-backend:$TRAVIS_JOB_ID;
            docker tag dsmovie-frontend:latest $DOCKER_USERNAME/dsmovie-frontend:$TRAVIS_JOB_ID;
            docker push $DOCKER_USERNAME/dsmovie-backend:$TRAVIS_JOB_ID;
            docker push $DOCKER_USERNAME/dsmovie-frontend:$TRAVIS_JOB_ID;
          on:
            branch: main

    - language: node_js
      node_js: 16
      before_script:
        - cd frontend/
      script:
        - yarn install

notifications:
  email: false
