version: '3.4'
services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567"
    ports:
      - "54320:5432"
    volumes:
      - ./backend/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dsmovie-net
  backend:
    image: dsmovie-backend
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - dsmovie-net
  frontend:
    image: dsmovie-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "3000:3000"
    networks:
      - dsmovie-net
networks:
  dsmovie-net:
    driver: bridge
